# Generated by Django 3.2.9 on 2023-03-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
