# Generated by Django 4.1.7 on 2023-03-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0005_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to=""
            ),
        ),
    ]
